# Generated by Django 3.2 on 2021-04-19 00:36

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('valid_till', models.DateTimeField(default=Users.models.default_local)),
                ('pfp', models.ImageField(upload_to='images/')),
                ('is_creator', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, max_length=3)),
                ('blog_subscribe', models.BooleanField(default=False)),
                ('saved', models.ManyToManyField(to='Blog.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
