# Generated by Django 3.2 on 2021-04-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_by', to='Users.profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_for', to='Users.profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notifiedOn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentOn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOn', to='Blog.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='Users.Profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Users.profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='raters',
            field=models.ManyToManyField(related_name='raters', to='Users.Profile'),
        ),
    ]
