# Generated by Django 3.2 on 2021-04-17 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='aid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='raters',
            field=models.ManyToManyField(related_name='raters', to='Users.Profile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('msg', models.TextField()),
                ('noti_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noti_by', to='Users.profile')),
                ('noti_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noti_for', to='Users.profile')),
                ('notifiedOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.article')),
            ],
        ),
    ]
