# Generated by Django 3.2 on 2021-04-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210419_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replyTo',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentOn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentOn', to='Blog.article'),
        ),
    ]
